services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsd_transaction
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bsd_transaction"
      NODE_ENV: development
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: always

  test:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bsd_transaction"
      BASE_URL: http://api:3000
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma
      - ./tests:/tests/tests
      - ./test-results:/tests/test-results
      - ./playwright-report:/tests/playwright-report

volumes:
  postgres_data:
